name: Lint
on: [push, pull_request]
jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - uses: actions/checkout@v2
    - name: ESLint
      uses: Krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintFiles: "src"
        eslintConfig: ".eslintrc.json"
        eslintExt: "js"
    - name: Shellcheck
        uses: azohra/shell-linter@latest
