name: Lint
on: [push, pull_request]
jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to other actions
    - uses: actions/checkout@v2
    - name: ESLint
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run lint
    - name: Super Linter
      # allow super-linter to run when ESLint fails
      if: ${{ success() || failure() }}
      uses: github/super-linter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_BASH: true
        VALIDATE_BASH_EXEC: true
