name: Lint
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to other actions
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.2
      with:
        node-version: '12'
    - name: ESLint
      run: npm install && npm run lint
  super_linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Super Linter
      uses: github/super-linter@v4.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_BASH: true
        VALIDATE_BASH_EXEC: true
  eslint_fork:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: plastikmensch/eslint-check-action@testing
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintFiles: "src"
        eslintConfig: ".eslintrc.json"
        eslintExt: "js"
